import os

from dotenv import load_dotenv

load_dotenv()

CONFLUENCE_URL = os.getenv("CONFLUENCE_URL")
CONFLUENCE_USERNAME = os.getenv("CONFLUENCE_USERNAME")
CONFLUENCE_PASSWORD = os.getenv("CONFLUENCE_PASSWORD")

AZURE_BLOB_STORAGE_ACCOUNT_NAME = os.getenv("AZURE_BLOB_STORAGE_ACCOUNT_NAME")
AZURE_BLOB_STORAGE_ACCOUNT_KEY = os.getenv("AZURE_BLOB_STORAGE_ACCOUNT_KEY")
AZURE_BLOB_STORAGE_CONTAINER_NAME = os.getenv("AZURE_BLOB_STORAGE_CONTAINER_NAME")
