import os

from dotenv import load_dotenv

load_dotenv()

CONFLUENCE_URL = os.getenv("CONFLUENCE_URL")
CONFLUENCE_USERNAME = os.getenv("CONFLUENCE_USERNAME")
CONFLUENCE_PASSWORD = os.getenv("CONFLUENCE_PASSWORD")

AZURE_BLOB_STORAGE_ACCOUNT_NAME = os.getenv("AZURE_BLOB_STORAGE_ACCOUNT_NAME")
AZURE_BLOB_STORAGE_ACCOUNT_KEY = os.getenv("AZURE_BLOB_STORAGE_ACCOUNT_KEY")
AZURE_BLOB_STORAGE_CONTAINER_NAME = os.getenv("AZURE_BLOB_STORAGE_CONTAINER_NAME")

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_API_BASE = os.getenv("AZURE_OPENAI_API_BASE")
AZURE_OPENAI_COMPLETION_MODEL_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_COMPLETION_MODEL_DEPLOYMENT_NAME")
AZURE_OPENAI_CHAT_MODEL_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_CHAT_MODEL_DEPLOYMENT_NAME")

MYSQL_ADDRESS = os.getenv("MYSQL_ADDRESS")
MYSQL_USERNAME = os.getenv("MYSQL_USERNAME")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
